### ISSUE TITLE
Dart source code: new and type inference

### ISSUE THREAD

**Issue by n8crwlr** [adityadroid/Messio#12]
Hello,

thank you really much for this, i would really like to enjoy your ride :100:

There are some inconsitences using `new` or _variable declaration_ (_type inferences_).

I would like to request to omit `new` overall and to omit _type assignment_ where ever useful to shorten the code:

```dart
class _ConversationPageState extends State<ConversationPage> {
  // final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  final _scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
```

Good time to you ☺️

**Comment by adityadroid** [comment]
Thanks for pointing it out @n8crwlr . Fixed with 
https://github.com/adityadroid/Messio/pull/13
