### ISSUE TITLE
support needed - add Contact failed - no contact added in firebase

### ISSUE THREAD

**Issue by ludoo0d0a** [adityadroid/Messio#32]
Hi,

first great job !!

I'm stuck on #day-24-26 ; I cannot understand the "add contact" workflow.

Why did the method addContact(String username) calls on first line [getUser(username);](https://github.com/adityadroid/Messio/blob/f989704f3a/lib/providers/UserDataProvider.dart#L129) ??

And from the the list getContacts, we should read contacts from firebase
but I don't see where they are inserted in firebase.

At [line 99](https://github.com/adityadroid/Messio/blob/f989704f3a/lib/providers/UserDataProvider.dart#L99), app crashes because contact never exists as user in db...

```dart
for (String username in contacts) {
            print(username);
// This failed =>
//            String uid = await getUidByUsername(username);
//            DocumentSnapshot contactSnapshot = await userRef.document(uid).get();
//            contactList.add(Contact.fromFirestore(contactSnapshot));

// bad workaround =>
            contactList.add(Contact(uid, username, username));
          }
```

Thanks to help me to understand this part !

**Comment by adityadroid** [comment]
> Hi,
> 
> first great job !!
> 
> I'm stuck on #day-24-26 ; I cannot understand the "add contact" workflow.
> 
> Why did the method addContact(String username) calls on first line [getUser(username);](https://github.com/adityadroid/Messio/blob/f989704f3a/lib/providers/UserDataProvider.dart#L129) ??
> 
> And from the the list getContacts, we should read contacts from firebase
> but I don't see where they are inserted in firebase.
> 
> At [line 99](https://github.com/adityadroid/Messio/blob/f989704f3a/lib/providers/UserDataProvider.dart#L99), app crashes because contact never exists as user in db...
> 
> ```dart
> for (String username in contacts) {
>             print(username);
> // This failed =>
> //            String uid = await getUidByUsername(username);
> //            DocumentSnapshot contactSnapshot = await userRef.document(uid).get();
> //            contactList.add(Contact.fromFirestore(contactSnapshot));
> 
> // bad workaround =>
>             contactList.add(Contact(uid, username, username));
>           }
> ```
> 
> Thanks to help me to understand this part !

Hi, 
`getUser` is called to check if the user exists or not. If the user doesn't exist it'll throw a UserNotFoundException and will fail. Thus the crash you're talking about at line 99 will not happen because the username is always checked before adding.


```
@override
  Future<void> addContact(String username) async {
 // getUser is called to check if the user we're trying to add exists (It'll throw a UserNotFoundException if the user doesn't exist)
    await getUser(username);
    //create a node with the username provided in the contacts collection
    DocumentReference ref = fireStoreDb
        .collection(Paths.usersPath)
        .document(SharedObjects.prefs.get(Constants.sessionUid));
    //await to fetch user details of the username provided and set data
    var documentSnapshot = await ref.get();
    print(documentSnapshot.data);
    List<String> contacts = documentSnapshot.data['contacts'] != null
        ? List.from(documentSnapshot.data['contacts'])
        : List();
    if (contacts.contains(username)) {
      throw ContactAlreadyExistsException();
    }
    contacts.add(username);
    ref.updateData({'contacts': contacts});
  }

  @override
  Future<User> getUser(String username) async {
      //get uid of user using username form the username_uid_map collection. It'll be null in case the user doesn't exist
    String uid = await getUidByUsername(username);
    DocumentReference ref =
        fireStoreDb.collection(Paths.usersPath).document(uid); 
    DocumentSnapshot snapshot = await ref.get();

    if (snapshot.exists) {  // this method will fail in case the uid/ref is null.
      return User.fromFirestore(snapshot);
    } else {
      throw UserNotFoundException();
    }
  }
```

**Comment by ludoo0d0a** [comment]
ok thanks, this is clearly a wanted behavior.
So does it mean you can add a contact only if the username already exists in db (and so this contact has already logged on the device) ?

How to add a new user ?
I may have missed something.

**Comment by adityadroid** [comment]
> ok thanks, this is clearly a wanted behavior.
> So does it mean you can add a contact only if the username already exists in db (and so this contact has already logged on the device) ?
> 
> How to add a new user ?
> I may have missed something.

Yes. You can only add users who are already registered on the app. A new user is created every time someone signs up on the app. 
So say if person A signs up with username_A, only then a person B will be able to add him using username_A.

**Comment by adityadroid** [comment]
I think I've clarified your doubts. Feel free to open this issue back if needed.
