### ISSUE TITLE
BLOC Building Issue

### ISSUE THREAD

**Issue by talalkhan0195** [adityadroid/Messio#47]
I'm having a problem while creating blocs. Every time I create a package named blocs and add another package with name authentication, it automatically turns to blocs.authentication and try to add blocs using the plugin you suggested it forms lowercase lettered blocs with underscores
![messenger_app  F__FLUTTER_messenger_app  -  _lib_pages_RegisterPage dart  messenger_app  - Android Studio 18-Oct-19 1_07_19 AM](https://user-images.githubusercontent.com/49128719/67043914-93211600-f144-11e9-9897-1ed76dcc451b.png)
![messenger_app  F__FLUTTER_messenger_app  -  _lib_pages_RegisterPage dart  messenger_app  - Android Studio 18-Oct-19 1_07_19 AM](https://user-images.githubusercontent.com/49128719/67043924-96b49d00-f144-11e9-900a-f3e56db3b81c.png)

 and the RegisterPage.dart is also not recognizing that.

**Comment by talalkhan0195** [comment]
[lib.zip](https://github.com/adityadroid/Messio/files/3748260/lib.zip)

**Comment by talalkhan0195** [comment]
![messenger_app  F__FLUTTER_messenger_app  -  _lib_blocs_authentication_Bloc dart  messenger_app  - Android Studio 21-Oct-19 12_40_10 AM](https://user-images.githubusercontent.com/49128719/67165180-75012300-f39b-11e9-8be0-764a26bed012.png)

**Comment by adityadroid** [comment]
Can you post the entire project repo here? Including   /android files

**Comment by talalkhan0195** [comment]
Thanks.. The issue was resolved..
