### ISSUE TITLE
Repo won't build/compile

### ISSUE THREAD

**Issue by cc123** [adityadroid/Messio#61]
Here's the error messages:

n)

Compiler message:
/d:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/d:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

Here are my flutter details:

Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (4 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by primochen** [comment]
my flutter details:
Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (2 weeks ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3

pubspec.yaml
update   version
cloud_firestore: ^0.13.6 #Firebase Database
flushbar: ^1.10.4
 cached_network_image: ^2.0.0

android/app/build.gradle
mark 
//apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin

then

√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
but get whitescreen   
you can try it

**Comment by adityadroid** [comment]
Apologies for the late response!
The following PR fixes all these issues and gets the app to a running state again.
